[workspace]
members = [
    "youtube",
    "core",
    "logger",
]
authors = ["Hokanosekai"]
name = "ytbascii"
resolver = "1"

[profile.release]
lto = true
panic = 'abort'
incremental = false
codegen-units = 8