[package]
name = "core"
version = "0.1.0"
authors = ["Hokanosekai"]
edition = "2021"

[dependencies]
logger = { path = "../logger" }
tokio = { version = "1.12.0", features = ["full"] }
youtube = { path = "../youtube" }
ffmpeg-next = "6.0.0"
termion = "2.0.1"

