[package]
name = "core"
version = "0.1.0"
authors = ["Hokanosekai"]
edition = "2021"

[dependencies]
google-youtube3 = "*"
hyper = "0.14.27"
hyper-rustls = "0.24.1"
serde = "^1.0"
serde_json = "^1.0"
