[package]
name = "api"
version = "0.1.0"
authors = ["Hokanosekai"]
edition = "2021"

[dependencies]
logger = { path = "../logger" }
lazy_static = "1.4"
serde = "1.0"
serde_json = "1.0"
reqwest = { version = "^0.11", features = ["json"] }
futures = "0.3"